# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passwordui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import string
import random
import pyperclip as pc

characters = list(string.ascii_letters + string.digits + "!@#$%^&*()")


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 275)
        self.amount = QtWidgets.QSpinBox(Dialog)
        self.amount.setGeometry(QtCore.QRect(10, 20, 121, 42))
        self.amount.setObjectName("amount")
        self.generate = QtWidgets.QPushButton(Dialog)
        self.generate.setGeometry(QtCore.QRect(140, 20, 91, 41))
        self.generate.setObjectName("generate")
        self.result = QtWidgets.QTextBrowser(Dialog)
        self.result.setGeometry(QtCore.QRect(240, 20, 341, 41))
        self.result.setObjectName("result")
        self.log = QtWidgets.QTextBrowser(Dialog)
        self.log.setGeometry(QtCore.QRect(10, 70, 571, 192))
        self.log.setObjectName("log")

        self.retranslateUi(Dialog)
        self.generate.clicked.connect(self.main)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    
    def main(self):
    	try:
    		length = int(self.amount.text())
    		self.log.append("[+] Secure password requested")
    		random.shuffle(characters)

    		password = []
    		for i in range(length):
    			password.append(random.choice(characters))

    		random.shuffle(password)

    		self.log.append("[+] Secure password generated")
    		self.result.clear()
    		self.result.append("".join(password))
    		self.log.append('[+] Done')
    	except:
    		print('[X] Error')
    
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.generate.setText(_translate("Dialog", "Generate"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
