# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passswd.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import string
import random


## characters to generate password from
characters = list(string.ascii_letters + string.digits + "!@#$%^&*()")


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(491, 287)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.amount = QtWidgets.QLineEdit(self.centralwidget)
        self.amount.setGeometry(QtCore.QRect(20, 20, 61, 31))
        self.amount.setObjectName("amount")
        self.generate = QtWidgets.QPushButton(self.centralwidget)
        self.generate.setGeometry(QtCore.QRect(80, 20, 131, 31))
        self.generate.setObjectName("generate")
        self.passwd = QtWidgets.QTextBrowser(self.centralwidget)
        self.passwd.setGeometry(QtCore.QRect(210, 20, 261, 31))
        self.passwd.setObjectName("passwd")
        self.log = QtWidgets.QTextBrowser(self.centralwidget)
        self.log.setGeometry(QtCore.QRect(20, 60, 451, 192))
        self.log.setObjectName("log")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 491, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.generate.clicked.connect(self.main)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def main(self):
        try:
            ## length of password from the user
            length = int(self.amount.text())
            self.log.append('[+] Secure Password requested!')
            ## shuffling the characters
            random.shuffle(characters)
            
            ## picking random characters from the list
            password = []
            for i in range(length):
                password.append(random.choice(characters))

            ## shuffling the resultant password
            random.shuffle(password)

            ## converting the list to string
            ## printing the list
            self.log.append('[+] Secure Password generated!')
            self.passwd.clear()
            self.passwd.append("".join(password))
            self.log.append('[+] Done!')
        except:
            self.log.append('[X] Error!')
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.generate.setText(_translate("MainWindow", "generate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
